spring:
  application:
    name: CashCard
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:authz.pub
          audiences: cashcard-client
  logging:
    level:
      org.springframework.security: TRACE
